CREATE SCHEMA tarok AUTHORIZATION tarokuser;
ALTER ROLE tarokuser SET search_path TO tarok, public;

ALTER DEFAULT PRIVILEGES IN SCHEMA tarok
    GRANT ALL PRIVILEGES ON TABLES TO tarokuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA tarok
    GRANT ALL PRIVILEGES ON SEQUENCES TO tarokuser;

CREATE TABLE tarok.player (
    player_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE
);

INSERT INTO tarok.player (name, email) VALUES ('test', 'test@gmail.com');
COMMIT;